import Head from "next/head";
import { AspectRatio, Box, Container, Flex, Text } from "@chakra-ui/react";

import Header from "@/components/Header";
import TopBar from "@/components/TopBar";

import { HomeHeroCategories } from "@/components/HomeHeroCategories";
import { Categories } from "@/models/Categories";
import AdvantageSection from "@/components/AdvantageSection";
import Image from "next/image";

type Product = {
  id: number;
  title: string;
  price: number;
  description: string;
  category: string;
  image: string;
  rating: {
    count: number;
    rate: number;
  };
};

type Props = {
  products: Product[];
  categories: Categories[];
};

export default function Home({ products, categories }: Props) {
  return (
    <>
      <Head>
        <title>eCommerce projects</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <TopBar />
      <Box marginBottom="2rem">
        <Header />
      </Box>

      <main>
        <Container size="lg">
          {HomeHeroCategories(categories)}
          {/* <HomeHeroCategories categories={categories}></HomeHeroCategories> */}

          <AdvantageSection />
        </Container>

        <Box
          margin="2rem 0"
          width="255px"
          border="solid 1px"
          borderColor="gray.200"
        >
          <AspectRatio position="relative" ratio="1" maxWidth="100%">
            <Image
              src="https://fakestoreapi.com/img/81fPKd-2AYL._AC_SL1500_.jpg"
              alt=""
              fill="true"
              style={{ objectFit: "contain" }}
            />
          </AspectRatio>
          <Text>Fjallraven - Foldsack No. 1 Backpack, Fits 15 Laptops</Text>
          <Text>$ 38.00</Text>
        </Box>

        <ol>
          {products.map((product) => {
            return (
              <li key={product.id}>
                {/* <Image src={product.image} alt="" width={200} height={200} /> */}
                <strong>{product.title}</strong>
              </li>
            );
          })}
        </ol>
      </main>
    </>
  );
}

export async function getServerSideProps(context) {
  const products = await fetch("https://fakestoreapi.com/products").then(
    (res) => res.json()
  );
  const categories = await fetch(
    "https://fakestoreapi.com/products/categories"
  ).then((res) => res.json());

  return {
    props: { products, categories },
  };
}
